# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b62828bc43fd7e1fe599e9f3f275bddb33565f7a4405cb7d18c4b5cc116d3b28e41b0f30067d654aa33196e0151e44fdbcb9b6cbf9f8c19ccd529d03081e5cd5

test:
  secret_key_base: 4ade48aead314dae21b293658f61d1d94f27ec1e15f5f35ce5d313f4b72a5c899272a35fb184ade22369cf2f17058bf8cae03eb890f0620b81245c58fd49ce16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
